version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    restart: always
    image: postgres:14.7-alpine
    expose:
      - '5432'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]


  app:
    build: .
    tty: true
    env_file:
      - .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker -l info
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    env_file:
      - .env
    tty: true
    command: celery -A config beat -l info -S django
    depends_on:
      - redis
      - app

volumes:
  pgdata:
