# Generated by Django 5.0.1 on 2024-03-17 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('deed', models.CharField(max_length=255, verbose_name='Задача')),
                ('time', models.CharField(max_length=255, verbose_name='Время')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, verbose_name='Периодичность в днях')),
                ('reward', models.CharField(max_length=255, verbose_name='Награда')),
                ('time_to_complete', models.TimeField(blank=True, null=True, verbose_name='Время на выполнение')),
                ('pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pleasant', to='habits.habit', verbose_name='Приятная привычка')),
                ('tied_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
