# Generated by Django 5.0.1 on 2024-03-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_rename_deed_habit_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичность привычки'),
        ),
    ]
