# Generated by Django 5.0.1 on 2024-03-23 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_reminder',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True, verbose_name='Время последнего напоминания'),
        ),
    ]
